---
# ============================================
# SATELLITE ROLE - DEFAULT VARIABLES
# ============================================

# Satellite server details
satellite_server: "deathstar.{{ domain_name | default('northshore.local') }}"
satellite_organization: "Northshore"


# Activation keys based on OS version and environment
# Environment is detected from group membership (all-prod vs all-dev)
satellite_activation_key_rhel8_prod: "rhel8-prod"
satellite_activation_key_rhel8_nonprod: "rhel8-nonprod"
# satellite_activation_key_rhel9_prod: ""
satellite_activation_key_rhel9_nonprod: "rhel9-nonprod"

# Skip registration if already registered
satellite_skip_if_registered: true

