---
# ============================================
# FIREWALL ROLE - DEFAULT VARIABLES
# ============================================

# Firewall zone
firewall_zone: public

# Enable ICMP
firewall_enable_icmp: true

# Predefined SSH access sources
firewall_ssh_sources:
  - { name: "Danvers IS", address: "10.1.11.0/24" }
  - { name: "VPN", address: "10.7.1.0/24" }
  - { name: "Arkanis", address: "10.1.9.95/32" }
  - { name: "Satellite", address: "10.1.15.46/32" }
  - { name: "Fred Jumpbox", address: "10.1.9.236/32" }
  - { name: "Barghest", address: "10.1.15.50/32" }

# Remove SSH service from zone (we use rich rules instead)
firewall_remove_ssh_service: true
